# require 'mailgun'

class ExampleMailer < ActionMailer::Base

  def sample_email

    # @user = user
    mg_client = Mailgun::Client.new ENV["MG_API_KEY"]
    message_params = {from: "info@da-slidesho.ws",
                      to: "bclevin@gmail.com",
                      subject: "Testing Mailgun email sending...",
                      text: "This is an email generated by DA Slideshows, sent via Mailgun!",
                      }
    mg_client.send_message ENV["MG_DOMAIN"], message_params
    
  end



end
